services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20.12-alpine
    image: synetsis-web:latest
    container_name: synetsis-web
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      # SMTP/MAIL envs for the contact endpoint
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_TO: ${MAIL_TO}
    restart: unless-stopped
